### ISSUE TITLE
[v1.4.1] Crash when cheating an item (shift+clicking an item stat)

### ISSUE THREAD

**Issue by TheCSDev** [TheCSDev/mc-better-stats#12]
Crash report:
```java
java.lang.NoSuchMethodError: 'void net.minecraft.class_746.method_44099(java.lang.String)'
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.3)
	at thecsdev.betterstats.client.BetterStatsClient.sendChat(BetterStatsClient.java:21)
	at thecsdev.betterstats.client.gui.widget.stats.BSItemStatWidget.slashGiveItem(BSItemStatWidget.java:92)
	at thecsdev.betterstats.client.gui.widget.stats.BSItemStatWidget.mouseClicked(BSItemStatWidget.java:63)
	at net.minecraft.client.gui.ParentElement.mouseClicked(ParentElement:27)
	at thecsdev.betterstats.client.gui.screen.ScreenWithScissors.swsOn_mouseClicked(ScreenWithScissors.java:188)
	at thecsdev.betterstats.client.gui.screen.ScreenWithScissors.mouseClicked(ScreenWithScissors.java:170)
	at net.minecraft.client.Mouse.method_1611(Mouse:94)
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen:489)
	at net.minecraft.client.Mouse.onMouseButton(Mouse:94)
	at net.minecraft.client.Mouse.method_22686(Mouse:165)
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:103)
	at net.minecraft.client.Mouse.method_22684(Mouse:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem:197)
	at net.minecraft.client.util.Window.swapBuffers(Window:315)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1204)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:767)
	at net.minecraft.client.main.Main.method_44604(Main:244)
	at net.minecraft.client.main.Main.main(Main:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

**Comment by TheCSDev** [comment]
The crash appears to be caused by the new chatting system implemented in Minecraft 1.19.1+. The current `/give` system uses the 1.19 chatting system, causing the crash on higher versions. Will likely have to say goodbye to 1.19+ and move on to 1.19.1+.
